### ISSUE TITLE
Filtering fails when value is a reserved word

### ISSUE THREAD

**Issue by tfdavids** [outr/solr4s#1]
When filtering a field for a value which is a reserved word (e.g. `state.filter(value = "OR")`), Solr interprets the value as the reserved word, rather than a string. The offending line is here:

https://github.com/boodleai/lemur/blob/new_l2/search/src/main/scala/ai/boodle/lemur/search/VoterDataMaintenance.scala#L166

**Comment by darkfrog26** [comment]
@tfdavids, I no longer have access to that repository, and you probably shouldn't be posting links to private repos in open-source projects. ;)

**Comment by darkfrog26** [comment]
Released 1.0.5 including this patch

**Comment by tfdavids** [comment]
Whoops, sorry, pasted the wrong link -- thanks for the fix!
